export enum ProjectConfigKeyEnum {

    PROJECT_AUTH_TOKEN = "PROJECT_AUTH_TOKEN",

    DOMAIN_SCORING_CRITICAL = "DOMAIN_SCORING_CRITICAL",
    DOMAIN_SCORING_HIGH = "DOMAIN_SCORING_HIGH",
    DOMAIN_SCORING_MEDIUM = "DOMAIN_SCORING_MEDIUM",
    DOMAIN_SCORING_LOW = "DOMAIN_SCORING_CRITICAL",
}

